MovieMonkey.Web/ViewModels/Search/PaginationViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace MovieMonkey.Web.ViewModels.Search
{
    public class PaginationViewModel
    {
        public IList<PageViewModel> Pages { get; set; }
        public IList<PageViewModel> PageWindow { get; set; }
        public string GoNextUrl { get; set; }
        public string GoPreviousUrl { get; set; }
        
        public long PageCount => Pages?.Count ?? 0;

        public bool CanGoPrevious
        {
            get { return Pages != null && Pages.Any(x => x.PageNumber == 1 && !x.Selected); }
        }

        public bool CanGoNext
        {
            get { return Pages != null && Pages.Any(x => x.PageNumber == PageCount && !x.Selected); }
        }
    }
}

MovieMonkey.Web/Controllers/SearchController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using MovieMonkey.Core.Services;
using MovieMonkey.Models.Models;
using MovieMonkey.Web.ActionFilters;
using MovieMonkey.Web.ViewModels.Mappers;
using MovieMonkey.Web.ViewModels.Search;
using MovieMonkey.Web.ViewModels.Search.Mappers;
using Ninject.Extensions.Logging;

namespace MovieMonkey.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger _logger;
        private readonly IMovieDataService _movieDataService;
        private readonly ISearchRequestMapper _searchRequestMapper;
        private readonly ISearchResponseMapper _searchResponseMapper;
        private readonly IPostbackHelper _postbackHelper;

        public SearchController(ILogger logger, IMovieDataService movieDataService, ISearchRequestMapper searchRequestMapper, 
            ISearchResponseMapper searchResponseMapper, IPostbackHelper postbackHelper)
        {
            _logger = logger;
            _movieDataService = movieDataService;
            _searchRequestMapper = searchRequestMapper;
            _searchResponseMapper = searchResponseMapper;
            _postbackHelper = postbackHelper;
        }

        [CookieActionFilter(Name = Constants.Cookie.BackToSearchResults)]
        [Route("search")]
        public async Task<ActionResult> IndexAsync(SearchQueryViewModel searchQueryViewModel)
        {
            var searchResults =
                await _movieDataService.SearchMovieAsync(_searchRequestMapper.Map(searchQueryViewModel));

            return View("~/Views/Search/Index.cshtml", _searchResponseMapper.Map(searchResults));
        }

        [Route("search"), HttpPost]
        public async Task<ActionResult> IndexAsync(SearchResponseViewModel searchResponseViewModel)
        {
            var searchResults =
                await _movieDataService.SearchMovieAsync(_searchRequestMapper.Map(searchResponseViewModel));

            return Redirect(_postbackHelper.GeneratePostbackSearchUrl(searchResponseViewModel.SearchRequest));
        }
    }
}

MovieMonkey.Web/Views/Partials/_Pagination.cshtml
@model MovieMonkey.Web.ViewModels.Search.PaginationViewModel

<div class="row text-center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            @if (Model.CanGoPrevious)
            {
                <li>
                    <a href="@Model.GoPreviousUrl" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }
            else
            {
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&laquo;</span>
                    </span>
                </li>
            }

            @foreach (var page in Model.PageWindow)
            {
                if (page.Selected)
                {
                    <li class="active">
                        <span>@page.Display<span class="sr-only">(current)</span></span>
                    </li>
                }
                else
                {
                    <li>
                        <a href="@page.PageUrl">@page.Display</a>
                    </li>
                }
            }

            @if (Model.CanGoNext)
            {
                <li>
                    <a href="@Model.GoNextUrl" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
            else
            {
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&raquo;</span>
                    </span>
                </li>
            }
        </ul>
    </nav>
</div>

MovieMonkey.Web/Views/Partials/_Refinement.cshtml
@model MovieMonkey.Web.ViewModels.Search.SearchResponseViewModel

@using (Html.BeginForm("IndexAsync", "Search", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SearchRequest.Limit)
    @Html.HiddenFor(x => x.SearchRequest.Offset)
    @Html.HiddenFor(x => x.SearchRequest.Sort)
    <div class="refinement">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <h4>Providers</h4>
                @Html.EditorFor(x => x.SearchRequest.Providers)
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <h4>Price Range</h4>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon">$</span>
                            @Html.TextBoxFor(x => x.SearchRequest.MinPrice, new {@class = "form-control", @placeholder = "Min Price"})
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon">$</span>
                            @Html.TextBoxFor(x => x.SearchRequest.MaxPrice, new { @class = "form-control", @placeholder = "Max Price" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <h4>Keywords</h4>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group form-group-sm">
                            @Html.TextBoxFor(x => x.SearchRequest.Keywords, new { @class = "form-control" })
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <input type="submit" class="btn btn-primary btn-sm" value="Update">
            </div>
        </div>
    </div>
}

MovieMonkey.Web/Views/Partials/_Results.cshtml
@using MovieMonkey.Core.Extensions
@model MovieMonkey.Web.ViewModels.Search.SearchResponseViewModel
<div class="search-results-container">
    <div class="row result-header">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h1>Found @Model.Total movies</h1>
        </div>
    </div>
    @Html.Partial("~/Views/Partials/_Pagination.cshtml", Model.Pagination)
    <div class="row">
        @foreach (var item in Model.SearchResults)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <a href="/details/@item.Id/@item.Title.ToSeoUrl(true)">
                    <div class="result-card">
                        <div class="card-image">
                            <img class="img-responsive" style="width: 100%;" src="https://images-na.ssl-images-amazon.com/images/M/MV5BNDRkYzA4OGYtOTBjYy00YzFiLThhYmYtMWUzMDBmMmZkM2M3XkEyXkFqcGdeQXVyNDYyMDk5MTU@('@')._V1_SX300.jpg" />
                        </div>
                        <div class="card-header">
                            <h3>@item.Title</h3>
                        </div>
                        <div class="card-body">
                            <h3>@item.Price</h3>
                            <div class="secondary-content">
                                <strong>Rating: </strong><span class="box-icon rating">@item.Rating</span>
                            </div>
                        </div>
                        <div class="card-footer">
                            Year: @item.Year | Runtime: @item.Runtime | Provider: @item.Provider
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
    @Html.Partial("~/Views/Partials/_Pagination.cshtml", Model.Pagination)
</div>

MovieMonkey.Web/Views/Partials/_SidebarNav.cshtml
<div class="sidebar-nav">
    <div class="sidebar-content">
        <div class="sidebar-content-header">
            <div class="">
                <span>
                    <a href="#" class="overlay-sidebar-close"><i class="icon icon-cancel"></i></a>
                </span>
            </div>
        </div>
        <div class="sidebar-content-body">
            <ul>
                <li><a href="#">About</a></li>
                <li><a href="#">Project Assumptions</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="overlay-cover"></div>

MovieMonkey.Web/Views/Partials/_TopBar.cshtml
@model MovieMonkey.Web.ViewModels.Search.SearchQueryViewModel


@using (Html.BeginForm("Index", "Home"))
{
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="top-bar-primary">
            <div class="row">
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-2">
                    <a href="/"><i class="icon icon-home3"></i></a>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-8">
                    <div class="input-group">
                        @Html.TextBoxFor(x => x.Keywords, new {@class = "form-control", @placeholder = "Find cheapest movies from different providers", aria_describedby = "basic-addon2"})
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit"><i class="icon icon-search"></i></button>
                        </span>
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-2" style="text-align: right;">
                    <a href="#" class="overlay-sidebar"><i class="icon icon-menu"></i></a>
                </div>
            </div>
        </div>
    </nav>
}

@Html.Partial("~/Views/Partials/_SidebarNav.cshtml")

MovieMonkey.Web/Views/Partials/_TopBarSecondary.cshtml
@model MovieMonkey.Web.ViewModels.Search.SearchResponseViewModel
<div class="top-bar-secondary">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4">
        <span class="left-content search-filter">
            <i class="icon icon-filter"></i>
            Filters&nbsp;
            <i class="icon icon-chevron-right"></i>
        </span>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4">
        <div class="dropdown left-content search-sort">
            <span class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class="icon icon-sort-amount-desc"></i>&nbsp;Sort
            </span>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                @foreach (var item in Model.SortOption.Options)
                {
                    <li class="@(item.Selected ? "active" : string.Empty)">
                        <a href="@item.Url">@item.Display</a>
                    </li>
    }
            </ul>
        </div>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4">
        <div class="dropdown left-content search-sort">
            <span class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class="icon icon-list-ordered"></i>&nbsp;Display
            </span>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                @foreach (var item in Model.DisplayLimit.DisplayLimits)
                {
                    <li class="@(item.Selected ? "active" : string.Empty)">
                        <a href="@item.Url">@item.Display</a>
                    </li>
    }

            </ul>
        </div>
    </div>
</div>